#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "stirling-pdf"
name = "Stirling PDF"
description.en = "Application that allows you to perform various operations on PDF files"
description.fr = "Application qui vous permet d'effectuer diverses opérations sur des fichiers PDF"

version = "0.29.0~ynh3"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://www.stirlingpdf.com/"
demo = "https://stirlingpdf.io/"
admindoc = "https://github.com/Stirling-Tools/Stirling-PDF/blob/main/LocalRunGuide.md"
userdoc = "https://docs.stirlingpdf.com/"
code = "https://github.com/Stirling-Tools/Stirling-PDF"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["de-DE", "fr-FR", "en-US"]
    default = "fr-FR"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    rename= "Stirling-PDF.jar"
    url = "https://github.com/Stirling-Tools/Stirling-PDF/releases/download/v0.29.0/Stirling-PDF.jar"
    sha256 = "93641da96c075f7ef1c1d594d4d2cb62633f1dfc340a495216634a5a6b53da3d"

    # autoupdate.strategy = "latest_github_tag"

    [resources.sources.jdk]
    amd64.url = "https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.13%2B11/OpenJDK17U-jdk_x64_linux_hotspot_17.0.13_11.tar.gz"
    amd64.sha256 = "8682892fc02965930b9022c066fa164dd6f458ef4a5dc262016aa28333b30f49"
    arm64.url = "https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.13%2B11/OpenJDK17U-jdk_arm_linux_hotspot_17.0.13_11.tar.gz"
    arm64.sha256 = "e69d43be937e05dbccae4cc98f732ed86aa11993234bf5ad6e81c30475a78ce7"
    autoupdate.strategy = "latest_github_release"
    autoupdate.version_regex = "jdk-(\\d+\\.\\d+\\.\\d+)\\+(.*)"
    autoupdate.upstream = "https://github.com/adoptium/temurin21-binaries"
    autoupdate.asset.amd64 = "OpenJDK.*-jdk_x64_linux_hotspot_.*\\.tar\\.gz$"
    autoupdate.asset.arm64 = "OpenJDK.*-jdk_aarch64_linux_hotspot_.*\\.tar\\.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "tesseract-ocr-fra, libreoffice-writer, libreoffice-calc, libreoffice-impress, unpaper, ocrmypdf"
